import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="w-full bg-[var(--element-color)] h-16 p-2">
          <ul className="w-full h-full flex justify-end items-center gap-x-4">
            <li><Link href="/dashboard">Home</Link></li>
            <li><Link href="/auth/login">Login</Link></li>
            <li><Link href="/auth/register">Sign up</Link></li>
            <li><Link href="/profile">Profile</Link></li>
            </ul>
            </nav>
        {children}
      </body>
    </html>
  );
}
