import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/app/[lng]/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Collections Manager",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <div className="w-full h-screen flex flex-col">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
